method: grid
metric:
  goal: minimize
  name: best_val_loss
entity: multimodal-supernovae
project: multimodal
parameters:
  dropout:
    values: [0.0002238697908102654]
  n_out:
    values: [32]
  # CNN
  cnn_depth:
    values: [2]
  cnn_dim:
    values: [32]
  cnn_channels:
    values: [3]
  cnn_kernel_size:
    values: [5]
  cnn_patch_size:
    values: [10]
  # Lightcurve transformer
  transformer_depth:
    values: [5]
  emb:
    values: [64]
  heads:
    values: [8]
  time_norm:
    values: [20583.369161312577]
  agg:
    values: [mean]
  # Spectral transformer
  emb_spectral:
    values: [32]
  transformer_depth_spectral:
    values: [13]
  heads_spectral:
    values: [2]
  time_norm_spectral:
    values: [17945.142213594805]
  agg_spectral:
    values: [mean]
  # Optimiser 
  lr:
    values: [3.716367614864064e-05]
  batchsize:
    values: [32]
  epochs:
    values: [1000]
  weight_decay:
    values: [0.000555522900788888]
  logit_scale:
    values: [19.545966923442453]
  seed:
    values: [0]
  patience:    # Parameter for early stopping 
    values: [9999]
sweep:
  id: rielcbld
# Options are 'lightcurve' 'spectral' and 'host_galaxy' -- order does not matter 
extra_args:
  combinations: [lightcurve, spectral]
  regression: false
  nruns: 1
  max_spectral_data_len: 1024
  val_fraction: 0.05  # train test split
  classification: false
  spectral_rescalefactor: 1 # rescaling spectral values by a fixed amout to avoid floating point issues
