method: grid
metric:
  goal: minimize
  name: best_val_loss
project: multimodal
parameters:
  dropout:
    values: [0.05, 0.1]
  lr:
    values: [1e-4, 5e-4]
  batchsize:
    values: [32]
  transformer_depth:
    values: [1, 2]
  emb:
    values: [32]
