agg: mean
agg_spectral: mean
batchsize: 32
cnn_channels: 3
cnn_depth: 16
cnn_dim: 32
cnn_kernel_size: 5
cnn_patch_size: 10
dataset_length: 4
dropout: 0.0001988
emb: 32
emb_spectral: 32
epochs: 2500
foldnumber: 2
heads: 2
heads_spectral: 2
logit_scale: 20000
lr: 1e-05
n_out: 32
noisy_masked_pretrain: None
patience: 99999999
seed: 0
time_norm: 3371.1677601717206
time_norm_spectral: 8946.72886036674
transformer_depth: 9
transformer_depth_spectral: 8
weight_decay: 0
