agg: mean
agg_spectral: mean
batchsize: 256
cnn_channels: 3
cnn_depth: 16
cnn_dim: 32
cnn_kernel_size: 5
cnn_patch_size: 10
dropout: 0.0001988
emb: 32
emb_spectral: 32
epochs: 1000
heads: 2
heads_spectral: 2
logit_scale: 20
lr: 0.0001
n_out: 32
patience: 9999
seed: 0
time_norm: 3371.1677601717206
time_norm_spectral: 8946.72886036674
transformer_depth: 9
transformer_depth_spectral: 8
weight_decay: 0
