method: grid
metric:
  goal: minimize
  name: best_val_loss
entity: multimodal-supernovae
project: multimodal
parameters:
  dropout:
    values: [0.0001988]
  n_out:
    values: [32]
  # CNN
  cnn_depth: 
    values: [16]
  cnn_dim:
    values: [32]
  cnn_channels:
    values: [3]
  cnn_kernel_size: 
    values: [5]
  cnn_patch_size:
    values: [10]
  # Lightcurve transformer
  transformer_depth:
    values: [9]
  emb:
    values: [32]
  heads:
    values: [2]
  time_norm: 
    values: [3371.1677601717206]
  agg: 
    values: ["mean"]
  # Spectral transformer
  emb_spectral:
    values: [32]
  transformer_depth_spectral:
    values: [8]
  heads_spectral:
    values: [2]
  time_norm_spectral:
    values: [8946.72886036674]
  agg_spectral:
    values: ["mean"]
  # Optimiser 
  lr:
    values: [1e-3]
  batchsize:
    values: [8192]
  epochs:
    values: [20]
  weight_decay:
    values: [0]
  logit_scale:
    values: [20.]
  seed:
    values: [0]
  patience:    # Parameter for early stopping 
    values: [99999999]
  dataset_length:
    values: [100000]
# Options are 'lightcurve' 'spectral' and 'host_galaxy' -- order does not matter 
extra_args:
  combinations: ["lightcurve"]
  regression: True
  nruns: 20
  max_spectral_data_len: 1024
  val_fraction: 0.05  # train test split
  classification: False
  spectral_rescalefactor: 1 # rescaling spectral values by a fixed amout to avoid floating point issues
  # Loading up pretrained weights for lc
  #pretrain_lc_path: 'models/pretrained_sim_lc/divine-sweep-1/epoch=394-step=4740.ckpt'
  #freeze_backbone_lc: True