batchsize: 256
# Parameter for lightcurve transformer
dropout: 0
emb: 32
transformer_depth: 1
# Parameter for lightcurve transformer
emb_spectral: 32 
transformer_depth_spectral: 1 
epochs: 50
lr: 0.0001
weight_decay: 0
seed: 0
# Options are 'lightcurve' 'spectral' and 'host_galaxy' -- order does not matter 
combinations: ['spectral','lightcurve']
