method: grid
metric:
  goal: minimize
  name: best_val_loss
entity: multimodal-supernovae
project: multimodal
parameters:
  dropout:
    values: [0.001]
  n_out:
    values: [32]
  # Lightcurve transformer
  transformer_depth:
    values: [1]
  emb:
    values: [32]
  heads:
    values: [2]
  # Spectral transformer
  emb_spectral:
    values: [32]
  transformer_depth_spectral:
    values: [1]
  heads_spectral:
    values: [2]
  # Optimiser 
  lr:
    values: [1e-4]
  batchsize:
    values: [256]
  epochs:
    values: [50]
  weight_decay:
    values: [0.01]
  seed:
    values: [0]
# Options are 'lightcurve' 'spectral' and 'host_galaxy' -- order does not matter 
extra_args:
  combinations: ["lightcurve", "spectral"] 
  nruns: 20
  max_spectral_data_len: 1000
