method: grid
metric:
  goal: minimize
  name: best_val_loss
project: multimodal
parameters:
  dropout:
    values: [0.001,0.005]
  lr:
    values: [1e-4]
  batchsize:
    values: [32]
  transformer_depth:
    values: [1]
  emb:
    values: [32]
  epochs:
    values: [600]
