batchsize: 256
dropout: 0
emb: 32
epochs: 50
lr: 0.0001
transformer_depth: 1
weight_decay: 0
seed: 0
# Options are 'lightcurve' 'spectral' and 'host_galaxy' -- order does not matter 
combinations: ['spectral','lightcurve']
